[package]
name = "appattest-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.0", features = ["json"] }
rand = "0.8"
app-attest = { git = "https://github.com/kayleegeorge/app-attest" }
tokio = { version = "1", features = ["full"] }
tokio-postgres = "0.7"
dotenv = "0.15"
rocket_sync_db_pools = { version = "0.1.0", features = ["diesel"] }
rocket_contrib = "0.2.4"

[dependencies.rocket_db_pools]
version = "0.1.0"
features = ["sqlx_sqlite"]

[default.databases.sqlite_logs]
url = "/path/to/database.sqlite"

